HairSalon/Models/Client.cs
namespace HairSalon.Models
{
    public class Client
    {
        public int ClientId { get; set; }

        public string Name { get; set; }

        public string PhoneNumber { get; set; }

        public string StyleHair { get; set; }

        public int StylistId { get; set; }

        public virtual Stylist Stylist { get; set; }
    }
}

HairSalon/Models/HairSalonContext.cs
using Microsoft.EntityFrameworkCore;

namespace HairSalon.Models
{
    public class HairSalonContext : DbContext
    {
        public virtual DbSet<Stylist> Stylists { get; set; }

        public DbSet<Client> Clients { get; set; }

        public HairSalonContext(DbContextOptions options) : base(options) { }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseLazyLoadingProxies();
        }
    }
}

HairSalon/Models/Stylist.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System;

namespace HairSalon.Models
{
    public class Stylist
    {
        public Stylist()
        {
            this.Clients = new HashSet<Client>();
        }

        public int StylistId { get; set; }

        public string Name { get; set; }

        [DisplayFormat(DataFormatString = "0:MM/dd/yyyy")]

        public DateTime HireDate { get; set; }

        public virtual ICollection<Client> Clients { get; set; }
    }
}

HairSalon/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Microsoft .EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using HairSalon.Models;

namespace HairSalon.Controllers
{
  public class ClientsController : Controller
  {
    private readonly HairSalonContext _db;
    
    public ClientsController(HairSalonContext db)
    {
      _db = db;
    }
    
    public ActionResult Index()
    {
      List<Client> model = _db.Clients.Include(client => client.Stylist).ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Client client)
    {
      _db.Clients.Add(client);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      return View(thisClient);
    }

    public ActionResult Edit(int id)
    {
      var thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      return View(thisClient);
    }

    [HttpPost]
    public ActionResult Edit(Client client)
    {
      _db.Entry(client).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      return View(thisClient);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      _db.Clients.Remove(thisClient);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

HairSalon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace HairSalon.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet("/")]
        public ActionResult Index()
        {
            return View();
        }
    }
}

HairSalon/Controllers/StylistsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Microsoft .EntityFrameworkCore;
using HairSalon.Models;

namespace HairSalon.Controllers
{
  public class StylistsController : Controller
  {
    private readonly HairSalonContext _db;
    
    public StylistsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Stylist> model = _db.Stylists.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Stylist stylist)
    {
      _db.Stylists.Add(stylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    public ActionResult Edit(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    [HttpPost]
    public ActionResult Edit(Stylist stylist)
    {
      _db.Entry(stylist).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      _db.Stylists.Remove(thisStylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

HairSalon/Views/Clients/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h2>Add A New Client</h2>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name, "Name:")
  @Html.TextBoxFor(model => model.Name)
  @Html.LabelFor(model => model.PhoneNumber, "Phone Number:")
  @Html.TextBoxFor(model => model.PhoneNumber)
  @Html.LabelFor(model => model.StyleHair, "What do you want to do today?")
  @Html.TextBoxFor(model => model.StyleHair)
  @Html.LabelFor(model => model.Stylist, "Stylist Name:")
  @Html.DropDownList("StylistId")

  <input type="submit" value="addNewClient" class="btn-default" />

}

<p>@Html.ActionLink("Show All Clients", "Index")</p>

HairSalon/Views/Clients/Delete.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h2>Are you sure you want to delete this client?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

@Html.ActionLink("Back to Client List", "Index")

HairSalon/Views/Clients/Details.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h2>Clients Details</h2>

<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<ul>
  <li>Phone Number: @Html.DisplayFor(model => model.PhoneNumber)</li>
  <li>Style Hair: @Html.DisplayFor(model => model.StyleHair)</li>
</ul>

<p>@Html.ActionLink("Edit Clients", "Edit", new {id = Model.ClientId})</p>
<p>@Html.ActionLink("Delete Clients", "Delete", new {id = Model.ClientId})</p>
<p>@Html.ActionLink("Back to Stylists", "Index", "Stylists")</p>
<p>@Html.ActionLink("Back to all Clients", "Index")</p>
<p>@Html.ActionLink("Back Home", "Index", "Home")</p>

HairSalon/Views/Clients/Edit.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client;

<h2>Edit Client:@Html.DisplayFor(model => model.Name)</h2>

<hr />
@using (Html.BeginForm())
{
  @Html.HiddenFor(model =>model.ClientId)

  @Html.LabelFor(model => model.Name, "Name:")
  @Html.EditorFor(model => model.Name)

  @Html.LabelFor(model => model.PhoneNumber, "Phone Number:")
  @Html.EditorFor(model => model.PhoneNumber)

  @Html.LabelFor(model => model.StyleHair, "Style Hair:")
  @Html.EditorFor(model => model.StyleHair)

  @Html.LabelFor(model => model.Stylist, "Stylist Name:")
  @Html.DropDownList("StylistId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to all Clients", "Index")</p>

HairSalon/Views/Clients/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model List<HairSalon.Models.Client>;

<h2>Client List</h2>

<hr />
@if (@Model.Count == 0)
{
  <h2>No Clients have been added yet!</h2>
}

<ul>
  @foreach (Client client in Model)
  {
    <li>@Html.ActionLink($"{client.Name}", "Details", new {id = client.ClientId})</li>
  }
</ul>

<p>@Html.ActionLink("Add new Client", "Create")</p>
<p>@Html.ActionLink("Back to Home", "Index", "Home")</p>

HairSalon/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1> Welcome EUA CLARIE to your salon database</h1>

<p>@Html.ActionLink("See your Stylists", "Index", "Stylists")</p>
<p>@Html.ActionLink("See your Clients", "Index", "Clients")</p>

HairSalon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>EAU CLARIE SALON</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    <div class="container">
    @RenderBody()
    </div>
  </body>
</html>

HairSalon/Views/Shared/footer.cshtml
<div id="footer"></div>

HairSalon/Views/Stylists/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist;

<h2>Add New Stylist</h2>

<hr />
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.LabelFor(model => model.HireDate)
  @Html.TextBoxFor(model => model.HireDate, new { type = "date"})

  <input type="submit" value="Add new Stylist" />
}

<p>@Html.ActionLink("Show all Stylist", "Index")</p>
<p>@Html.ActionLink("Back to Home", "Index", "Home")</p>

HairSalon/Views/Stylists/Delete.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h2>Are you sure you want to delete this Stylist?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

@Html.ActionLink("Back to Stylist List", "Index")

HairSalon/Views/Stylists/Details.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models
@model HairSalon.Models.Stylist


<h2>Stylists Details</h2>

<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<h5>Due Date: @Convert.ToDateTime(Model.HireDate).ToString("MM/dd/yyyy")</h5>

<H6>Clients for this Stylist</H6>

<ul>
  @foreach (Client client in Model.Clients)
  {
    <li>@Html.ActionLink($"{client.Name}", "Details", "Clients", new {id = client.ClientId})</li>
  }
</ul>



<p>@Html.ActionLink("Edit Stylists", "Edit", new {id = Model.StylistId})</p>
<p>@Html.ActionLink("Delete Stylists", "Delete", new {id = Model.StylistId})</p>
<p>@Html.ActionLink("Back to Stylists", "Index")</p>
<p>@Html.ActionLink("Add Clients", "Create", "Clients")</p>
<p>@Html.ActionLink("Back to home", "Index", "Home")</p>

HairSalon/Views/Stylists/Edit.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h2>Edit Stylist:@Html.DisplayFor(model => model.Name)</h2>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model =>model.StylistId)

  @Html.LabelFor(model => model.Name, "Name:")
  @Html.EditorFor(model => model.Name)

  @Html.LabelFor(model => model.HireDate, "Hire Date:")
  @Html.EditorFor(model => model.HireDate)

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to all Stylists", "Index")</p>

HairSalon/Views/Stylists/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model List<HairSalon.Models.Stylist>;

<h2>Stylist List</h2>

<hr />
@if (@Model.Count == 0)
{
  <h2>No Stylists have been added yet!</h2>
}

<ul>
  @foreach (Stylist stylist in Model)
  {
    <li>@Html.ActionLink($"{stylist.Name}", "Details", new {id = stylist.StylistId})</li>
  }
</ul>

<p>@Html.ActionLink("Add new Stylist", "Create")</p>
<p>@Html.ActionLink("Back to Home", "Index", "Home")</p>